project_id = "wddeivyttkciiyrnbcti"

[functions.daily-investment-reminder]
verify_jwt = false

[functions.market-data]
verify_jwt = false

[functions.weekly-profit-clear]
verify_jwt = false

[functions.track-visit]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

